<Project Sdk="Microsoft.NET.Sdk">

	<PropertyGroup>
		<OutputType>Exe</OutputType>
		<TargetFramework>net8.0</TargetFramework>
		<ImplicitUsings>enable</ImplicitUsings>
		<Nullable>enable</Nullable>
		<BaseOutputPath>../bin</BaseOutputPath>
		<LangVersion>preview</LangVersion>
		<AllowUnsafeBlocks>true</AllowUnsafeBlocks>
		<IncludeNativeLibrariesForSelfExtract>true</IncludeNativeLibrariesForSelfExtract>
		<!-- uncomment this to default to packaging a single file --snark5885  -->
		<!-- <PublishSingleFile>true</PublishSingleFile> -->
	</PropertyGroup>

	<!-- RuntimeIdentifier gets populated with its proper -r linux-x64 flag (or whatever), linux is defined, and conts.cs should resolve all its directory fields properly --snark5885 -->
	<PropertyGroup Condition="$(RuntimeIdentifier.StartsWith('win'))">
		<DefineConstants>$(DefineConstants);WINDOWS</DefineConstants>
	</PropertyGroup>
	<PropertyGroup Condition="$(RuntimeIdentifier.StartsWith('linux'))">
		<DefineConstants>$(DefineConstants);LINUX</DefineConstants>
	</PropertyGroup>

	<ItemGroup>
		<PackageReference Include="CsvHelper" Version="33.1.0" />
		<PackageReference Include="JsonRepairSharp" Version="1.2.4" />
		<PackageReference Include="Magick.NET-Q8-AnyCPU" Version="14.16.0" />
		<PackageReference Include="Newtonsoft.Json" Version="13.0.5-beta1" />
		<PackageReference Include="OpenTK" Version="4.9.4" />
		<PackageReference Include="ShellProgressBar" Version="5.2.0" />
		<PackageReference Include="Spectre.Console" Version="0.57.2" />
	</ItemGroup>

	<!-- move DDSCreator and the other stuff to bin so we don't have to move it manually afterward --snark5885 -->
	<Target Name="MoveExeToBin" AfterTargets="Publish">
		<ItemGroup>
			<FilesToBin Include="$(PublishDir)$(AssemblyName)" Condition="Exists('$(PublishDir)$(AssemblyName)')" />
			<FilesToBin Include="$(PublishDir)$(AssemblyName).exe" Condition="Exists('$(PublishDir)$(AssemblyName).exe')" />
			<FilesToBin Include="$(PublishDir)$(AssemblyName).pdb" Condition="Exists('$(PublishDir)$(AssemblyName).pdb')" />
			<FilesToBin Include="$(PublishDir)SharpShaders.pdb" Condition="Exists('$(PublishDir)SharpShaders.pdb')"/>
		</ItemGroup>
		<MakeDir Directories="$(PublishDir)bin" />
		<Move SourceFiles="@(FilesToBin)" DestinationFolder="$(PublishDir)bin" />
	</Target>

	<ItemGroup>
		<Content Include="..\**\*.*" Exclude="..\DDSCreator\**\*.*;
..\src\**\*.*;
..\AutoGenerated\**\*.*;
..\Other\**\*.*;

..\UI\**\*.*;
..\VFXCommons\**\*.*;
..\Commons\**\*.*;
..\docs\**\*.*;
..\Deprecated\**\*.*;

..\External\SharpShaders\**\*.*;

..\scripts\**\*.*;

..\AGENTS.md;
..\TODO.md;
..\TODO.txt;

..\.dds_metadata.json;
..\Promotional\**\*.*;

..\.github\**\*.*;
..\.idea\**\*.*;
..\.run\**\*.*;

..\.git\**\*.*;
..\.gitignore;
..\.gitmodules;
..\.markdownlint.jsonc;
..\_icon.jpg;

..\bin\**\*.*;
..\out\**\*.*;
">
			<CopyToOutputDirectory>Always</CopyToOutputDirectory>
			<CopyToPublishDirectory>Always</CopyToPublishDirectory>
			<ExcludeFromSingleFile>true</ExcludeFromSingleFile>
			<Link>%(RecursiveDir)%(FileName)%(Extension)</Link>
		</Content>
	</ItemGroup>

	<ItemGroup>
	  <Reference Include="SharpShaders">
	    <HintPath>..\External\SharpShaders\bin\Debug\net8.0\SharpShaders.dll</HintPath>
	  </Reference>
	</ItemGroup>

</Project>
